language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=allegro
    - LISP=sbcl
    - LISP=sbcl32
    - LISP=ccl
    - LISP=ccl32
    - LISP=clisp
    - LISP=clisp32
    - LISP=cmucl
    - LISP=ecl

matrix:
  allow_failures:
    # CIM not available for CMUCL
    - env: LISP=cmucl
    # Reported upstream bugs
    - env: LISP=allegro
    - env: LISP=clisp
    - env: LISP=clisp32
    - env: LISP=ecl

# uses a local script. Felt free to simplify this section in my own file.
install:
    ./travis-install.sh;
    sudo apt-get install libssl-dev libssl0.9.8:i386

# this serves as a poor example of how to use the 'cl' script (provided by
# CIM) to test your Lisp project. Here, we're not using any test framework
# to do unit testing; real frameworks should have various ways of determining
# whether a test suite fails or succeeds, but don't hold your breath.
script:
  - cl -e '(ql:quickload :scalpl) (asdf:load-system :scalpl.mpex) (uiop:quit 0))'
